version: '2'
services:
  db:
    image: postgres
    volumes:
      - "../db/db_ticket/01_create_db_ticket.sql:/docker-entrypoint-initdb.d/01.sql"
      - "../db/db_ticket/10_insert_data_db_ticket.sql:/docker-entrypoint-initdb.d/10.sql"
    environment:
      - POSTGRES_DB=db_ticket
      - POSTGRES_USER=ticket
      - POSTGRES_PASSWORD=ticket
  web:
    build: ./
    links:
      - "db:database"
    volumes:
      - ../ticket/ticket-webapp/target/ticket-webapp.war:/usr/local/tomcat/webapps/ticket-webapp.war
    ports:
      - "8000:8000"
      - "8080:8080"

